### ISSUE TITLE
Error  snailpub.py  ((

### ISSUE THREAD

**Issue by Grayesso** [iceland2k14/snail#3]
Traceback (most recent call last):
  File "c:\GitHub\_Puzzles\snail-main\snailpub.py", line 35, in <module>
    puzz_h160 = [ice.pub2upub(line).hex() for line in puzz.values()]
  File "c:\GitHub\_Puzzles\snail-main\snailpub.py", line 35, in <listcomp>
    puzz_h160 = [ice.pub2upub(line).hex() for line in puzz.values()]
AttributeError: module 'secp256k1' has no attribute 'pub2upub'

**Comment by seega** [comment]
https://github.com/iceland2k14/snail#requirements
